// Code generated by mockery v2.53.7. DO NOT EDIT.

package patient

import (
	context "context"

	entity "github.com/khaimook/hospital-middleware/entity"
	mock "github.com/stretchr/testify/mock"

	patient "github.com/khaimook/hospital-middleware/repository/patient"

	util "github.com/khaimook/hospital-middleware/util"
)

// MockPatientService is an autogenerated mock type for the PatientService type
type MockPatientService struct {
	mock.Mock
}

type MockPatientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPatientService) EXPECT() *MockPatientService_Expecter {
	return &MockPatientService_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: ctx, hospitalID, hospitalCode, params
func (_m *MockPatientService) Search(ctx context.Context, hospitalID uint, hospitalCode string, params patient.SearchParams) ([]entity.PatientResponse, *util.AppError) {
	ret := _m.Called(ctx, hospitalID, hospitalCode, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []entity.PatientResponse
	var r1 *util.AppError
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, patient.SearchParams) ([]entity.PatientResponse, *util.AppError)); ok {
		return rf(ctx, hospitalID, hospitalCode, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, patient.SearchParams) []entity.PatientResponse); ok {
		r0 = rf(ctx, hospitalID, hospitalCode, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PatientResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, patient.SearchParams) *util.AppError); ok {
		r1 = rf(ctx, hospitalID, hospitalCode, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*util.AppError)
		}
	}

	return r0, r1
}

// MockPatientService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockPatientService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - hospitalID uint
//   - hospitalCode string
//   - params patient.SearchParams
func (_e *MockPatientService_Expecter) Search(ctx interface{}, hospitalID interface{}, hospitalCode interface{}, params interface{}) *MockPatientService_Search_Call {
	return &MockPatientService_Search_Call{Call: _e.mock.On("Search", ctx, hospitalID, hospitalCode, params)}
}

func (_c *MockPatientService_Search_Call) Run(run func(ctx context.Context, hospitalID uint, hospitalCode string, params patient.SearchParams)) *MockPatientService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(patient.SearchParams))
	})
	return _c
}

func (_c *MockPatientService_Search_Call) Return(_a0 []entity.PatientResponse, _a1 *util.AppError) *MockPatientService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPatientService_Search_Call) RunAndReturn(run func(context.Context, uint, string, patient.SearchParams) ([]entity.PatientResponse, *util.AppError)) *MockPatientService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPatientService creates a new instance of MockPatientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPatientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPatientService {
	mock := &MockPatientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
