// Code generated by mockery v2.53.7. DO NOT EDIT.

package patient

import (
	context "context"

	entity "github.com/khaimook/hospital-middleware/entity"
	mock "github.com/stretchr/testify/mock"

	patient "github.com/khaimook/hospital-middleware/repository/patient"
)

// MockPatientRepository is an autogenerated mock type for the PatientRepository type
type MockPatientRepository struct {
	mock.Mock
}

type MockPatientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPatientRepository) EXPECT() *MockPatientRepository_Expecter {
	return &MockPatientRepository_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: ctx, hospitalID, params
func (_m *MockPatientRepository) Search(ctx context.Context, hospitalID uint, params patient.SearchParams) ([]entity.Patient, error) {
	ret := _m.Called(ctx, hospitalID, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []entity.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, patient.SearchParams) ([]entity.Patient, error)); ok {
		return rf(ctx, hospitalID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, patient.SearchParams) []entity.Patient); ok {
		r0 = rf(ctx, hospitalID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, patient.SearchParams) error); ok {
		r1 = rf(ctx, hospitalID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPatientRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockPatientRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - hospitalID uint
//   - params patient.SearchParams
func (_e *MockPatientRepository_Expecter) Search(ctx interface{}, hospitalID interface{}, params interface{}) *MockPatientRepository_Search_Call {
	return &MockPatientRepository_Search_Call{Call: _e.mock.On("Search", ctx, hospitalID, params)}
}

func (_c *MockPatientRepository_Search_Call) Run(run func(ctx context.Context, hospitalID uint, params patient.SearchParams)) *MockPatientRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(patient.SearchParams))
	})
	return _c
}

func (_c *MockPatientRepository_Search_Call) Return(_a0 []entity.Patient, _a1 error) *MockPatientRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPatientRepository_Search_Call) RunAndReturn(run func(context.Context, uint, patient.SearchParams) ([]entity.Patient, error)) *MockPatientRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, _a1
func (_m *MockPatientRepository) Upsert(ctx context.Context, _a1 *entity.Patient) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Patient) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPatientRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockPatientRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Patient
func (_e *MockPatientRepository_Expecter) Upsert(ctx interface{}, _a1 interface{}) *MockPatientRepository_Upsert_Call {
	return &MockPatientRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, _a1)}
}

func (_c *MockPatientRepository_Upsert_Call) Run(run func(ctx context.Context, _a1 *entity.Patient)) *MockPatientRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Patient))
	})
	return _c
}

func (_c *MockPatientRepository_Upsert_Call) Return(_a0 error) *MockPatientRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPatientRepository_Upsert_Call) RunAndReturn(run func(context.Context, *entity.Patient) error) *MockPatientRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPatientRepository creates a new instance of MockPatientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPatientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPatientRepository {
	mock := &MockPatientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
