// Code generated by mockery v2.53.7. DO NOT EDIT.

package staff

import (
	context "context"

	entity "github.com/khaimook/hospital-middleware/entity"
	mock "github.com/stretchr/testify/mock"

	util "github.com/khaimook/hospital-middleware/util"
)

// MockStaffService is an autogenerated mock type for the StaffService type
type MockStaffService struct {
	mock.Mock
}

type MockStaffService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStaffService) EXPECT() *MockStaffService_Expecter {
	return &MockStaffService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, username, password, hospitalCode
func (_m *MockStaffService) Create(ctx context.Context, username string, password string, hospitalCode string) (*entity.StaffResponse, *util.AppError) {
	ret := _m.Called(ctx, username, password, hospitalCode)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.StaffResponse
	var r1 *util.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*entity.StaffResponse, *util.AppError)); ok {
		return rf(ctx, username, password, hospitalCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *entity.StaffResponse); ok {
		r0 = rf(ctx, username, password, hospitalCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.StaffResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) *util.AppError); ok {
		r1 = rf(ctx, username, password, hospitalCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*util.AppError)
		}
	}

	return r0, r1
}

// MockStaffService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStaffService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - hospitalCode string
func (_e *MockStaffService_Expecter) Create(ctx interface{}, username interface{}, password interface{}, hospitalCode interface{}) *MockStaffService_Create_Call {
	return &MockStaffService_Create_Call{Call: _e.mock.On("Create", ctx, username, password, hospitalCode)}
}

func (_c *MockStaffService_Create_Call) Run(run func(ctx context.Context, username string, password string, hospitalCode string)) *MockStaffService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockStaffService_Create_Call) Return(_a0 *entity.StaffResponse, _a1 *util.AppError) *MockStaffService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStaffService_Create_Call) RunAndReturn(run func(context.Context, string, string, string) (*entity.StaffResponse, *util.AppError)) *MockStaffService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password, hospitalCode
func (_m *MockStaffService) Login(ctx context.Context, username string, password string, hospitalCode string) (string, *util.AppError) {
	ret := _m.Called(ctx, username, password, hospitalCode)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *util.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, *util.AppError)); ok {
		return rf(ctx, username, password, hospitalCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, username, password, hospitalCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) *util.AppError); ok {
		r1 = rf(ctx, username, password, hospitalCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*util.AppError)
		}
	}

	return r0, r1
}

// MockStaffService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockStaffService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - hospitalCode string
func (_e *MockStaffService_Expecter) Login(ctx interface{}, username interface{}, password interface{}, hospitalCode interface{}) *MockStaffService_Login_Call {
	return &MockStaffService_Login_Call{Call: _e.mock.On("Login", ctx, username, password, hospitalCode)}
}

func (_c *MockStaffService_Login_Call) Run(run func(ctx context.Context, username string, password string, hospitalCode string)) *MockStaffService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockStaffService_Login_Call) Return(_a0 string, _a1 *util.AppError) *MockStaffService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStaffService_Login_Call) RunAndReturn(run func(context.Context, string, string, string) (string, *util.AppError)) *MockStaffService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStaffService creates a new instance of MockStaffService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStaffService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStaffService {
	mock := &MockStaffService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
