// Code generated by mockery v2.53.7. DO NOT EDIT.

package admin

import (
	context "context"

	util "github.com/khaimook/hospital-middleware/util"
	mock "github.com/stretchr/testify/mock"
)

// MockAdminService is an autogenerated mock type for the AdminService type
type MockAdminService struct {
	mock.Mock
}

type MockAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminService) EXPECT() *MockAdminService_Expecter {
	return &MockAdminService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockAdminService) Login(ctx context.Context, username string, password string) (string, *util.AppError) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *util.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, *util.AppError)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *util.AppError); ok {
		r1 = rf(ctx, username, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*util.AppError)
		}
	}

	return r0, r1
}

// MockAdminService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAdminService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAdminService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockAdminService_Login_Call {
	return &MockAdminService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockAdminService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockAdminService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAdminService_Login_Call) Return(_a0 string, _a1 *util.AppError) *MockAdminService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminService_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, *util.AppError)) *MockAdminService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminService creates a new instance of MockAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminService {
	mock := &MockAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
