// Code generated by mockery v2.53.7. DO NOT EDIT.

package his

import (
	context "context"

	his "github.com/khaimook/hospital-middleware/client/his"
	mock "github.com/stretchr/testify/mock"
)

// MockHISClient is an autogenerated mock type for the HISClient type
type MockHISClient struct {
	mock.Mock
}

type MockHISClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHISClient) EXPECT() *MockHISClient_Expecter {
	return &MockHISClient_Expecter{mock: &_m.Mock}
}

// SearchPatient provides a mock function with given fields: ctx, hospitalCode, id
func (_m *MockHISClient) SearchPatient(ctx context.Context, hospitalCode string, id string) (*his.HISPatient, error) {
	ret := _m.Called(ctx, hospitalCode, id)

	if len(ret) == 0 {
		panic("no return value specified for SearchPatient")
	}

	var r0 *his.HISPatient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*his.HISPatient, error)); ok {
		return rf(ctx, hospitalCode, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *his.HISPatient); ok {
		r0 = rf(ctx, hospitalCode, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*his.HISPatient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, hospitalCode, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHISClient_SearchPatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPatient'
type MockHISClient_SearchPatient_Call struct {
	*mock.Call
}

// SearchPatient is a helper method to define mock.On call
//   - ctx context.Context
//   - hospitalCode string
//   - id string
func (_e *MockHISClient_Expecter) SearchPatient(ctx interface{}, hospitalCode interface{}, id interface{}) *MockHISClient_SearchPatient_Call {
	return &MockHISClient_SearchPatient_Call{Call: _e.mock.On("SearchPatient", ctx, hospitalCode, id)}
}

func (_c *MockHISClient_SearchPatient_Call) Run(run func(ctx context.Context, hospitalCode string, id string)) *MockHISClient_SearchPatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockHISClient_SearchPatient_Call) Return(_a0 *his.HISPatient, _a1 error) *MockHISClient_SearchPatient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHISClient_SearchPatient_Call) RunAndReturn(run func(context.Context, string, string) (*his.HISPatient, error)) *MockHISClient_SearchPatient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHISClient creates a new instance of MockHISClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHISClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHISClient {
	mock := &MockHISClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
