// Code generated by mockery v2.53.7. DO NOT EDIT.

package hospital

import (
	context "context"

	entity "github.com/khaimook/hospital-middleware/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockHospitalRepository is an autogenerated mock type for the HospitalRepository type
type MockHospitalRepository struct {
	mock.Mock
}

type MockHospitalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHospitalRepository) EXPECT() *MockHospitalRepository_Expecter {
	return &MockHospitalRepository_Expecter{mock: &_m.Mock}
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *MockHospitalRepository) FindByCode(ctx context.Context, code string) (*entity.Hospital, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *entity.Hospital
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Hospital, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Hospital); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Hospital)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHospitalRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockHospitalRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockHospitalRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *MockHospitalRepository_FindByCode_Call {
	return &MockHospitalRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *MockHospitalRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *MockHospitalRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHospitalRepository_FindByCode_Call) Return(_a0 *entity.Hospital, _a1 error) *MockHospitalRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHospitalRepository_FindByCode_Call) RunAndReturn(run func(context.Context, string) (*entity.Hospital, error)) *MockHospitalRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHospitalRepository creates a new instance of MockHospitalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHospitalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHospitalRepository {
	mock := &MockHospitalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
