// Code generated by mockery v2.53.7. DO NOT EDIT.

package staff

import (
	context "context"

	entity "github.com/khaimook/hospital-middleware/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockStaffRepository is an autogenerated mock type for the StaffRepository type
type MockStaffRepository struct {
	mock.Mock
}

type MockStaffRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStaffRepository) EXPECT() *MockStaffRepository_Expecter {
	return &MockStaffRepository_Expecter{mock: &_m.Mock}
}

// CreateWithHospital provides a mock function with given fields: ctx, _a1, hospitalID
func (_m *MockStaffRepository) CreateWithHospital(ctx context.Context, _a1 *entity.Staff, hospitalID uint) error {
	ret := _m.Called(ctx, _a1, hospitalID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithHospital")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Staff, uint) error); ok {
		r0 = rf(ctx, _a1, hospitalID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStaffRepository_CreateWithHospital_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithHospital'
type MockStaffRepository_CreateWithHospital_Call struct {
	*mock.Call
}

// CreateWithHospital is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Staff
//   - hospitalID uint
func (_e *MockStaffRepository_Expecter) CreateWithHospital(ctx interface{}, _a1 interface{}, hospitalID interface{}) *MockStaffRepository_CreateWithHospital_Call {
	return &MockStaffRepository_CreateWithHospital_Call{Call: _e.mock.On("CreateWithHospital", ctx, _a1, hospitalID)}
}

func (_c *MockStaffRepository_CreateWithHospital_Call) Run(run func(ctx context.Context, _a1 *entity.Staff, hospitalID uint)) *MockStaffRepository_CreateWithHospital_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Staff), args[2].(uint))
	})
	return _c
}

func (_c *MockStaffRepository_CreateWithHospital_Call) Return(_a0 error) *MockStaffRepository_CreateWithHospital_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStaffRepository_CreateWithHospital_Call) RunAndReturn(run func(context.Context, *entity.Staff, uint) error) *MockStaffRepository_CreateWithHospital_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *MockStaffRepository) FindByUsername(ctx context.Context, username string) (*entity.Staff, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *entity.Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Staff, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Staff); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStaffRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockStaffRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockStaffRepository_Expecter) FindByUsername(ctx interface{}, username interface{}) *MockStaffRepository_FindByUsername_Call {
	return &MockStaffRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockStaffRepository_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockStaffRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStaffRepository_FindByUsername_Call) Return(_a0 *entity.Staff, _a1 error) *MockStaffRepository_FindByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStaffRepository_FindByUsername_Call) RunAndReturn(run func(context.Context, string) (*entity.Staff, error)) *MockStaffRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// HasHospital provides a mock function with given fields: ctx, staffID, hospitalID
func (_m *MockStaffRepository) HasHospital(ctx context.Context, staffID uint, hospitalID uint) (bool, error) {
	ret := _m.Called(ctx, staffID, hospitalID)

	if len(ret) == 0 {
		panic("no return value specified for HasHospital")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (bool, error)); ok {
		return rf(ctx, staffID, hospitalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) bool); ok {
		r0 = rf(ctx, staffID, hospitalID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, staffID, hospitalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStaffRepository_HasHospital_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasHospital'
type MockStaffRepository_HasHospital_Call struct {
	*mock.Call
}

// HasHospital is a helper method to define mock.On call
//   - ctx context.Context
//   - staffID uint
//   - hospitalID uint
func (_e *MockStaffRepository_Expecter) HasHospital(ctx interface{}, staffID interface{}, hospitalID interface{}) *MockStaffRepository_HasHospital_Call {
	return &MockStaffRepository_HasHospital_Call{Call: _e.mock.On("HasHospital", ctx, staffID, hospitalID)}
}

func (_c *MockStaffRepository_HasHospital_Call) Run(run func(ctx context.Context, staffID uint, hospitalID uint)) *MockStaffRepository_HasHospital_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockStaffRepository_HasHospital_Call) Return(_a0 bool, _a1 error) *MockStaffRepository_HasHospital_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStaffRepository_HasHospital_Call) RunAndReturn(run func(context.Context, uint, uint) (bool, error)) *MockStaffRepository_HasHospital_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStaffRepository creates a new instance of MockStaffRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStaffRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStaffRepository {
	mock := &MockStaffRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
